name: 'Build AUR Package'
description: 'Build an AUR package in Docker container'
branding:
  icon: user-check
  color: gray-dark
inputs:
  package-source:
    description: 'AUR package source (Git URL or local path)'
    required: true
  custom-repo:
    description: 'Custom repository to add to pacman.conf'
    required: false
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.package-source }}
    - ${{ inputs.custom-repo }}